### ISSUE TITLE
Datasets availability 

### ISSUE THREAD

**Issue by danieltomasz** [TomDonoghue/EEGFOOOF#1]
Hi @TomDonoghue!

Do you know if  is there any chance that  the EEG dataset you used or its subset  will be publicly available? 
This would be a great help  for students who could  even more easily  learn about fooof while  playing  with  the code  you  placed here

Thanks for you great  work and for effort for preparing these notebooks :)

**Comment by TomDonoghue** [comment]
Ahh, sorry @danieltomasz - I appear to have missed this question. 

The EEG dataset in this particular analysis is an old one that I didn't record so I'm not 100% sure about if I can make it totally openly available. 

In general though, we are working on more analyses that will soon be public, with public datasets. 

One that's already available with code & open data is this one: https://github.com/voytekresearch/bandratios
